<<<<<<< HEAD
markdown: rdiscount
pygments: true
=======
name: Douglas Wei's Home Site
markdown: redcarpet
pygments: true
auto: true

redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'space_after_headers']
>>>>>>> b65fff3fca81448f2dd68d2515e518a4a894e828
